export default {
  Guilds: 1 << 0,
  Guild_Members: 1 << 1,
  Guild_Moderation: 1 << 2,
  Guild_Emojis_And_Stickers: 1 << 3,
  Guild_Integrations: 1 << 4,
  Guild_Webhooks: 1 << 5,
  Guild_Invites: 1 << 6,
  Guild_Voice_States: 1 << 7,
  Guild_Presences: 1 << 8,
  Guild_Messages: 1 << 9,
  Guild_Message_Reactions: 1 << 10,
  Guild_Message_Typing: 1 << 11,
  Direct_Messages: 1 << 12,
  Direct_Message_Reactions: 1 << 13,
  Direct_Message_Typing: 1 << 14,
  Message_Content: 1 << 15,
  Guild_Scheduled_Events: 1 << 16,
  Auto_Moderation_Configuration: 1 << 20,
  Auto_Moderation_Execution: 1 << 21,
};
